# Array tipai ir konvertavimas

In [1]:
import numpy as np

> Kiekvieną kartą kai naudosim NumPy, mes naudosim np prefiksą. Tai tiesiog standartinis numpy naming convention.

In [2]:
integers = np.array([10,20,30,40,50])
integers

array([10, 20, 30, 40, 50])

## Pirma reikšmė

In [4]:
integers[0]

10

> Taip pat kaip ir Python listas, čia indeksavimas yra zero-based (prasideda nuo nulio)

## Pakeisti reikšmę

In [5]:
integers[0] = 20
integers

array([20, 20, 30, 40, 50])

## Pakeisti reikšmę kitu duomenų tipu

In [6]:
integers[0] = 21.5
integers

array([21, 20, 30, 40, 50])

> Skaičius automatiškai sutrumpintas (nuimtas skaičius po kablelio). Tai yra todėl, kad NumPy array visi duomenys turi būti vienodo tipo.

## Patikrinti duomenų tipą

In [7]:
integers.dtype

dtype('int32')

> Array taip pat gali būti: int32, int64, floating point numbers, unsigned integers, complex numbers.

## Pakeisti array duomenų tipą

In [8]:
smaller_integers = np.array(integers, dtype=np.int8)
smaller_integers

array([21, 20, 30, 40, 50], dtype=int8)

## Pažiūrėti objektų dydžių skirtumus

In [9]:
integers.nbytes

20

In [10]:
smaller_integers.nbytes

5

> Turint tuos pačius elementus, smaller_integers naudoja 4 kartus mažiau atminties(memory).

## Neteisingai nurodomas duomenų tipas

In [11]:
overflow = np.array([127, 128, 129], dtype=np.int8)
overflow

array([ 127, -128, -127], dtype=int8)

> NumPy pakeičia reikšmes, kurios tenkina dtype.

## Automatinis nustatymas duomenų tipo

In [12]:
floats = np.array([1.2,2.3,3.4,4.5,5.6])
floats

array([1.2, 2.3, 3.4, 4.5, 5.6])

In [13]:
floats.dtype

dtype('float64')

> Net nenurodžius duomenų tipo, NumPy pats atpažino iš elementų, kad tai bus float64 tipas.