# Vidinis NumPy array kūrimas

In [2]:
import numpy as np

## NumPy Arange

In [2]:
?np.arange

### stop

In [3]:
integers_array = np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### start, stop

In [4]:
integers_second_array = np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

### start, stop, step

In [5]:
integers_third_array = np.arange(100,150,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148])

> Arange metodas naudojamas tik su integer tipo duomenimis

## NumPy Linspace

In [6]:
?np.linspace

### start, stop

In [7]:
first_floats_arr = np.linspace(10,20)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

> By default gavome 50 reikšmių, kurios yra nuo 10 iki 20

### start, stop, num

In [8]:
second_floats_arr = np.linspace(10,20,5)
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

> Matome, kad gavome 5 elemetus tarp kurių yra vienodi skirtumai

## Skirtumai tarp arange ir linspace

* arange naudoja trečią argumentą (step) kaip skaičių, kiek norime peršokti.
* linspace naudoja trečią argumentą (num) kaip skaičių kiek jų norime turėti.

## NumPy random.rand

In [9]:
?np.random.rand

### One-dimensional array

In [10]:
first_rand_arr = np.random.rand(10)
first_rand_arr

array([0.60707426, 0.41755835, 0.75950764, 0.9921991 , 0.31569261,
       0.82756296, 0.16552233, 0.8800543 , 0.5661847 , 0.5757213 ])

> Gavome 10 random skaičių, kurių reikšmės yra nuo 0 iki 1

### Two-dimensional array

In [11]:
second_rand_arr = np.random.rand(4,4)
second_rand_arr

array([[0.52662931, 0.25063931, 0.90835485, 0.6265006 ],
       [0.1958089 , 0.49417078, 0.84929992, 0.07939484],
       [0.28353548, 0.41039384, 0.93932554, 0.39546364],
       [0.93538268, 0.78563402, 0.34805082, 0.90333785]])

> Gavome 4 listus po 4 random reikšmes

## NumPy random.randint

In [3]:
?np.random.randint

### low, high, size

In [15]:
third_rand_arr = np.random.randint(0,100,20)
third_rand_arr

array([12, 49, 11, 61, 49, 60, 29, 45,  7, 23, 62, 49, 84, 70, 11, 50, 60,
       66, 13, 42])

> Gavome 20 random skaičių nuo 0 iki 100

In [16]:
third_rand_arr

array([12, 49, 11, 61, 49, 60, 29, 45,  7, 23, 62, 49, 84, 70, 11, 50, 60,
       66, 13, 42])