# Array su pastoviom reikšmėm

In [1]:
import numpy as np

## NumPy zeros

In [2]:
?np.zeros

### One-dimensional

In [3]:
first_z_array = np.zeros(5)
first_z_array

array([0., 0., 0., 0., 0.])

> Gauname array su 5 nuliukais

### Two-dimensional

In [4]:
second_z_array = np.zeros((4,5))
second_z_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

> Gauname dvimatį masyvą su 4 eilutėm ir 5 stulpeliais ir užpildytom nulinėm reikšmėm.

## NumPy Ones

In [5]:
?np.ones

### One-dimensional

In [6]:
first_ones_array = np.ones(6)
first_ones_array

array([1., 1., 1., 1., 1., 1.])

> Gauname array su 6 vienetukais

### Two-dimensional

In [7]:
second_ones_array = np.ones((7,8))
second_ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

> Gauname two-dimensional array su 7 eilutėm ir 8 stulpeliais ir užpildytais vienetukais

### Three-dimensional

In [8]:
third_ones_array = np.ones((4,5,2), dtype=int)
third_ones_array

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

> Gauname three-dim array ir šį kartą mūsų reikšmės yra integer tipo.

## NumPy Empty ir Fill

Fill metodas naudojamas tik su one-dimensional array. Norint naudoti fill metodą reikia turėti jau egzistuojantį array, todėl mes naudojam empty metodą sukurti tuščiam array.

In [13]:
?np.empty

In [11]:
?np.ndarray.fill

In [12]:
first_fill_array = np.empty(10, dtype=int)
first_fill_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
first_fill_array.fill(12)
first_fill_array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

> Gauname array su 10 dvyliktukų. 

## NumPy Full

Full metodas gali būti naudojamas tiek su one-dimensional, tiek su multi-dimensional

In [16]:
?np.full

### One-dimensional

In [17]:
first_full_array = np.full(5,10)
first_full_array

array([10, 10, 10, 10, 10])

> Gauname array su 5 dešimtukais

### Two-dimensional

In [18]:
second_full_array = np.full((4,5), 8)
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

> Gauname two-dimensional array užpildytą aštuonetais (4 eilutės ir 5 stulpeliai)