In [2]:
import numpy as np

1.	Sukurkite vektorių su skaičiais nuo 1 iki 10

In [4]:
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2.	Sukurkite vektorių iš 10 nulių

In [5]:
arr2=np.zeros(10)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3.	Sukurkite vektorių iš 10 vienetų

In [6]:
arr3=np.ones(10)
arr3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4.	Sukurkite vektorių iš 10 ketvertų

In [7]:
arr4 = np.full(10,4)
arr4

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

5.	Sukurkite vektorių iš lyginių skaičių nuo 0 iki 100

In [42]:
arr5 = np.arange(2,101,2)
arr5

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

6.	Sukurkite matricą iš 25 narių, pradedant 1, baigiant 25. Priskirkite ją kintamajam.

In [40]:
arr = np.arange(1,26)
arr6=np.array_split(arr5, 2)
arr6


[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])]

In [18]:
arr7=np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13], [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]])
arr7

C:\Users\emirug\AppData\Local\Temp\ipykernel_21560\2370758599.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr7=np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13], [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]])


array([list([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]),
       list([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])],
      dtype=object)

7.	Iš matricos ištraukite skaičių 12

In [21]:
arr7[0][11]

12

8.	Iš matricos ištraukite paskutinę eilutę.

In [22]:
arr7[1]

[14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

9.	Iš matricos ištraukite submatricą:
1, 2, 3\ 6, 7, 8\ 11,12,13


In [24]:
arr7[0][5:8]

[6, 7, 8]

10.	Iš matricos ištraukite submatricą:
7, 8, 9, 10\ 12, 13, 14, 15\ 17, 18, 19, 20

In [30]:
con_arr = np.concatenate((arr7[0][11:13], arr7[1][0:2]))
con_arr

array([12, 13, 14, 15])

11.	Iš matricos ištraukite submatricą:
16, 17, 18
21, 22, 23

In [33]:
arr7[1][2:11]

[16, 17, 18, 19, 20, 21, 22, 23, 24]

12.	Sukurkite vektorių iš 20 atsitiktinių reikšmių nuo 0 iki 1. Priskirkite kintamajam.

In [38]:
arr8 = np.random.randint(0,2,20)
arr8

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0])

13.	Suraskite didžiausią reikšmę masyve ir jos indeksą. (naudoti max() ir .argmax())

In [45]:
m=np.max(arr5)
m2=arr5.argmax()
print('Max reikšmė', m, 'Indeksas', m2)

Reikšmė 100 Indeksas 49


14.	Suraskite mažiausią reikšmę ir jos indeksą. (naudoti min() ir .argmin())

In [46]:
mn=np.min(arr5)
mn2=arr5.argmin()
print('Min reikšmė', mn, 'Indeksas', mn2)

Min reikšmė 2 Indeksas 0


15.	Atspausdinkite šios matricos duomenų tipą

In [59]:
arr7.dtype

dtype('O')